name: Test this and that on GitHub Actions

on:

  workflow_dispatch:
  push:

jobs:
  test_run:
    runs-on: ubuntu-latest

    steps:
    - name: Check the latest Rakudo release version
      id: rakudo-release
      # shell: bash
      run: |
        curl -v --stderr - https://github.com/rakudo/rakudo/releases/latest
