
name: Upload Rakudo-Star to Rakudo.org

on:
  schedule: # Allways (one day) later then the publishing of the Rakudo-Star releases at GH, Tuesdays and Friday, at 23:55 UTC
    - cron:  '55 23 * * 2,5'
  workflow_dispatch:
  
jobs:
  upload_star_release:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Get GitHub's Rakudo Star and the Rakudo.org versions
      id: rkd_v_check
      run: |
        RKD_STR_GH=$(curl -s https://raw.githubusercontent.com/AntonOks/star/master/RELEASE | awk -F "===>" '{print $1}')
        RKD_STR_ORG_TMP=$(curl -s https://rakudo.org/dl/star/ | jq -r '.[] | select((.latest==1) and (.url|test("-win-x86_64-")) and (.url|test("checksum")|not)) | .url')
        if [[ "$RKD_STR_ORG_TMP" =~ rakudo-star-([0-9]+.[0-9]+.?[0-9]?)-([0-9]+)- ]]; then
          echo ::set-output name=RKD_STR_VERSION::${BASH_REMATCH[1]}
          echo ::set-output name=RKD_STR_PATCH=${BASH_REMATCH[2]}
          RKD_STR_ORG="${BASH_REMATCH[1]}-${BASH_REMATCH[2]}"
        else
          echo "Couldn't get the RAKUDO.ORG Star version"
          exit
        fi
        echo "\$RKD_STR_GH is \"$RKD_STR_GH\" and \$RKD_STR_ORG is \"$RKD_STR_ORG\""
        if [[ "$RKD_STR_GH" != "$RKD_STR_ORG" ]]; then
          echo ::set-output name=publish::
        fi
        
    - name: Prepare ssh config
      id: ssh_config
      if: steps.rkd_v_check.outputs.publish
      run: |
        if [[ ! -d ~/.ssh ]]; then mkdir -m 700 -p ~/.ssh; fi
        echo "${{ secrets.ACTIONS_RAKUDO_ORG_CONFIG }}" | base64 -d > ~/.ssh/config
        chmod 600 ~/.ssh/config
        echo ::set-output name=config::'true'
        
    - name: Prepare ssh known_hosts
      if: steps.ssh_config.outputs.config
      run: |
        echo "${{ secrets.ACTIONS_RAKUDO_ORG_KNOWN_HOSTS }}" | base64 -d > ~/.ssh/known_hosts
        chmod 0600 ~/.ssh/known_hosts
        
    - name: Prepare ssh public key file
      if: steps.ssh_config.outputs.config
      run: |
        echo "${{ secrets.ACTIONS_RAKUDO_ORG_ED25519_PUB }}" | base64 -d > ~/.ssh/rakudo_id_ed25519.pub
        chmod 644 ~/.ssh/rakudo_id_ed25519.pub
        
    - name: Prepare ssh private key file
      if: steps.ssh_config.outputs.config
      run: |
        echo "${{ secrets.ACTIONS_RAKUDO_ORG_ED25519_PRIV }}" | base64 -d > ~/.ssh/rakudo_id_ed25519
        chmod 600 ~/.ssh/rakudo_id_ed25519
        
    - name: List my SSH stuff
      if: steps.ssh_config.outputs.config
      run: |
        echo "PWD is: $(pwd)"
        ls -laR ~/.ssh/*
        
    - name: Get the Rakudo Star files
      run: |
        mkdir ~/output && cd ~/output
        for FILE in `curl -s https://api.github.com/repos/rakudo/star/releases/tags/${{steps.rkd_v_check.outputs.RKD_STR_VERSION}} | jq -r ".assets[] | .browser_download_url"`; do
          echo "running curl -L $FILE"
          curl -L $FILE
        done
        ls -laR
       
    - name: Run SSH ls
      if: steps.ssh_config.outputs.config
      run: |
        ssh rakudo.org ls -l
        \rm -r ~/.ssh/*
