name: Update my scoop manifests

on:
  # schedule:
  #   - cron:  '10 6-22 * * *' # my working and online hours ;)
  workflow_dispatch:

jobs:
  update_manifests:
    runs-on: windows-2019
      
    steps:
    - name: Checkout my scoop-aoks repo
      uses: actions/checkout@v3
      with:
        repository: AntonOks/scoop-aoks
        path: scoop-aoks
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.head_ref }}
        fetch-depth: 0
        
    - name: Checkout Scoop
      uses: actions/checkout@v3
      with:
        repository: ScoopInstaller/Scoop
        path: 'scoop_core'
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        
    - name: Init and Test
      shell: pwsh
      run: |
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
        $env:SCOOP_HOME="$(Resolve-Path '.\scoop_core')"
        $env:PATH += ";$env:SCOOP_HOME\bin"
        .\scoop_core\lib\core.ps1
        .\scoop_core\test\bin\init.ps1
        .\scoop_core\bin\install.ps1
        ### .\scoop-aoks\bin\test.ps1 ### Need to correct ma stuff first :|
          
    - name: AutoUpdate manifests
      run: |
        ls -Recurse scoop-aoks
        & scoop help
        & scoop bucket add extras
        & scoop bucket add scoop-aoks https://github.com/AntonOks/scoop-aoks
        cd scoop-aoks
        & .\bin\Update-AutoupdateManifests.ps1 -V
      
    - name: Add and commit changes
      uses: EndBug/add-and-commit@v8
      with:
        message: "Updated the manifests at $(date)"
        push: "true"
