name: Update my scoop manifests

on:
  ### schedule:
  ###  - cron:  '10 6-22 * * *' # my working and online hours ;)
  workflow_dispatch:
  pull_request_target:

jobs:
  update_manifests:
    runs-on: windows-2019
    
    permissions: write-all
      
    steps:
    - name: Checkout my scoop-aoks repo
      uses: actions/checkout@v3
      with:
        repository: AntonOks/scoop-aoks
        path: 'scoop-aoks'
        persist-credentials: false
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.head_ref }}
        fetch-depth: 0
        
    - name: Checkout Scoop
      uses: actions/checkout@v3
      with:
        repository: ScoopInstaller/Scoop
        path: 'scoop_core'
        persist-credentials: false
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        
    - name: Init and Test... and now also Update my bucket
      shell: pwsh
      run: |
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
        
        ### $env:I_AM_A_GITHUB_ACTION=$True
        $env:SCOOP_HOME="$(Resolve-Path '.\scoop_core')"
        ### $env:PATH += ";$env:SCOOP_HOME\bin"
        
        echo "   INFO - Running `"git config -l`""
        git config -l
        
        git config --global user.email "github.bot@example.github.com"
        git config --global user.name "Github Bot"
        
        echo "   INFO - Running `".\scoop_core\lib\core.ps1`""
        .\scoop_core\lib\core.ps1
        
        echo "   INFO - Running `".\scoop_core\test\bin\init.ps1`""
        .\scoop_core\test\bin\init.ps1
        
        echo "   INFO - Running `".\scoop_core\bin\install.ps1`""
        .\scoop_core\bin\install.ps1
        
        ### .\scoop-aoks\bin\test.ps1 ### Need to correct my stuff first :|
        
        echo "   INFO - Adding `"extras`" and `"scoop-aoks`" buckets..."
        scoop bucket add extras
        scoop bucket add scoop-aoks https://github.com/AntonOks/scoop-aoks
        
        echo "   INFO - changing into the scoop-aoks directory"
        cd scoop-aoks
        
        echo "   INFO - showing the remote repos"
        git remote -v
        
        ### echo "   INFO - changing the remote origin to use my TOKEN"
        ### git remote set-url origin https://token:${{ secrets.ACTIONS_SECRET }}@github.com/AntonOks/scoop-aoks.git
        
        echo "   INFO - Try gh tool to authenticate "
        echo ${{ secrets.ACTIONS_SECRET }} > mytoken.txt
        $GH_AUTH = "gh auth login -p https --with-token"
        Invoke-Expression "$GH_AUTH -i < mytoken.txt"
        \rm -f mytoken.txt
        gh auth status
        
        echo "   INFO - run the AutoUpdate script"
        & .\bin\Update-AutoupdateManifests.ps1 -V
        
        echo "   INFO - save the date in the AUTOUPDATE file"
        $(date) > AUTOUPDATE
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        directory: '.\scoop-aoks'
        repository: AntonOks/scoop-aoks
        github_token: ${{ secrets.ACTIONS_SECRET }}
        ### branch: ${{ github.ref }}
      
    ### - name: Add finaly commit changes
    ###   uses: EndBug/add-and-commit@v9
    ###   with:
    ###      message: "Updated the manifests at $(date)"
    ###      cwd: '.\scoop-aoks'
    ###      push: "true"
