name: Update my scoop manifests

on:
  schedule:
    - cron:  '10 6-22 * * *' # my working and online hours ;)
  workflow_dispatch:

jobs:
  update_manifests:
    runs-on: windows-2019
    
    steps:
    - name: Checkout my scoop-aoks repo
      uses: actions/checkout@v3
      with:
        repository: AntonOks/scoop-aoks
        path: scoop-aoks
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.head_ref }}
        fetch-depth: 0
        
    - name: Install SCOOP
      run: |
        iwr -useb get.scoop.sh -outfile 'install.ps1'
        .\install.ps1 -RunAsAdmin
      # run: Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
        
    - name: AutoUpdate manifests
      run: |
        ls
        & $GITHUB_WORKSPACE\scoop-aoks\bin\Update-AutoupdateManifests.ps1 -V
      
    - name: Add and commit changes
      uses: EndBug/add-and-commit@v8
      with:
        message: "Updated the manifests at $(date)"
        push: "true"
