name: Update my scoop manifests

on:
  schedule:
    - cron:  '10 6-22 * * *' # my working and online hours ;)
  workflow_dispatch:

jobs:
  update_manifests:
    runs-on: windows-2019
      
    steps:
    - name: Checkout my scoop-aoks repo
      uses: actions/checkout@v3
      with:
        repository: AntonOks/scoop-aoks
        path: scoop-aoks
        token: ${{ secrets.ACTIONS_SECRET }}
        ref: ${{ github.head_ref }}
        ### fetch-depth: 0
        
    - name: Checkout Scoop
      uses: actions/checkout@v3
      with:
        repository: ScoopInstaller/Scoop
        path: 'scoop_core'
        token: ${{ secrets.ACTIONS_SECRET }}
        ### fetch-depth: 0
        
    - name: Init and Test... and now also Update my bucket
      shell: pwsh
      run: |
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
        $env:I_AM_A_GITHUB_ACTION=$True
        $env:SCOOP_HOME="$(Resolve-Path '.\scoop_core')"
        ### $env:PATH += ";$env:SCOOP_HOME\bin"
        
        git config --global user.email "github.bot@example.github.com"
        git config --global user.name "Github Bot"
        
        echo "Running `".\scoop_core\lib\core.ps1`""
        .\scoop_core\lib\core.ps1
        echo "Running `".\scoop_core\test\bin\init.ps1`""
        .\scoop_core\test\bin\init.ps1
        echo "Running `".\scoop_core\bin\install.ps1`""
        .\scoop_core\bin\install.ps1
        ### .\scoop-aoks\bin\test.ps1 ### Need to correct my stuff first :|
        echo "Adding \"extras\" and \"scoop-aoks\" buckets..."
        scoop bucket add extras
        scoop bucket add scoop-aoks https://github.com/AntonOks/scoop-aoks
        cd scoop-aoks
        & .\bin\Update-AutoupdateManifests.ps1 -V
        # $(date) > AUTOUPDATE
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACTIONS_SECRET }}
        branch: ${{ github.ref }}
      
    ### - name: Add finaly commit changes
    ###   uses: EndBug/add-and-commit@v9
    ###   with:
    ###     message: "Updated the manifests at $(date)"
    ###     cwd: "scoop-aoks"
    ###     push: "true"
